---
- name: check if user exists
  hosts: localhost
  vars_files:
    - secret.yml
  tasks:
    - name: check if "{{ username }}" exists
      user:
#        name: "{{ users.shadim.first_name }}"
        name: "{{ username }}"
        state: present

    - name: register and debug example
      command:
        cmd: date
      register: todays_date

    - debug:
        var: todays_date

